#!/bin/bash

COLOR_PREFIX="\e["

BLUE="${COLOR_PREFIX}34m"
RED="${COLOR_PREFIX}31m"
GREEN="${COLOR_PREFIX}32m"
PURPLE="${COLOR_PREFIX}35m"
CYAN="${COLOR_PREFIX}36m"
LIGHT_GRAY="${COLOR_PREFIX}37m"

INFO="${COLOR_PREFIX}1;37;46mINFO${COLOR_PREFIX}0m "
ERROR="${COLOR_PREFIX}1;37;41mERROR${COLOR_PREFIX}0m "
